EmployeeManagementSystem_bootstrap3/EmployeeManagementSystem/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.views.static import serve
from django.conf import settings

from app_web.views import department_views, employee_views, prettynum_views, admin_views, account_views, task_views, order_views, chart_views, upload_views, city_views


urlpatterns = [
    # path('admin/', admin.site.urls),

    # 启用media目录
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}, name='media'),
    # re_path是正则表达式

    # 部门管理
    path('department/list/', department_views.department_list),
    path('department/add/', department_views.department_add),
    path('department/model/form/add/', department_views.department_model_form_add),
    path('department/delete/', department_views.department_delete),
    path('department/edit/', department_views.department_edit),
    path('department/<int:nid>/edit/', department_views.department_edit),   # 通过url传递id
    path('department/batch_upload/', department_views.department_batch_upload),

    # 员工管理
    path('employee/list/', employee_views.employee_list),
    path('employee/add/', employee_views.employee_add),
    path('employee/model/form/add/', employee_views.employee_model_form_add),
    path('employee/<int:nid>/edit/', employee_views.employee_edit),
    # path('employee/<int:nid>/delete/', employee_views.employee_delete),
    path('employee/delete/', employee_views.employee_delete),


    # 靓号管理
    path('prettynum/list/', prettynum_views.prettynum_list),
    path('prettynum/model/form/add/', prettynum_views.prettynum_model_form_add),
    path('prettynum/<int:nid>/edit/', prettynum_views.prettynum_edit),
    # path('prettynum/<int:nid>/delete/', prettynum_views.prettynum_delete),
    path('prettynum/delete/', prettynum_views.prettynum_delete),


    # 管理员的管理
    path('admin/list/', admin_views.admin_list),
    path('admin/add/', admin_views.admin_add),
    path('admin/<int:nid>/edit/', admin_views.admin_edit),
    # path('admin/<int:nid>/delete/', admin_views.admin_delete),  # 用nid传参删除
    path('admin/delete/', admin_views.admin_delete),  # 用ajax传参删除
    path('admin/<int:nid>/reset_password/', admin_views.admin_reset_password),

    # 用户登录
    path('login/', account_views.login),
    path('logout/', account_views.logout),
    path('image/captcha/', account_views.image_captcha),

    # 任务管理
    path('task/list/', task_views.task_list),
    path('task/ajax/', task_views.task_ajax),  # 学习Ajax用到的路由
    path('task/add/', task_views.task_add),
    path('task/detail/', task_views.task_detail),
    path('task/edit/', task_views.task_edit),
    path('task/delete/', task_views.task_delete),


    # 订单管理
    path('order/list/', order_views.order_list),
    path('order/add/', order_views.order_add),
    path('order/delete/', order_views.order_delete),
    path('order/detail/', order_views.order_detail),
    path('order/edit/', order_views.order_edit),

    # 数据统计图表
    path('chart/list/', chart_views.chart_list),
    path('chart/line/', chart_views.chart_line),
    path('chart/bar/', chart_views.chart_bar),
    path('chart/pie/', chart_views.chart_pie),
    path('chart/highcharts/', chart_views.highcharts_example),

    # 上传文件
    path('upload/list/', upload_views.upload_list),
    path('upload/form/', upload_views.upload_form),
    path('upload/model/form/', upload_views.upload_model_form),

    # 城市列表
    path('city/list/', city_views.city_list),
    path('city/add/', city_views.city_add),

]

EmployeeManagementSystem_bootstrap3/app_web/models.py
from django.db import models


# Create your models here.

class Admin(models.Model):
    """ 管理员 """
    admin_name = models.CharField(verbose_name="管理员用户名", max_length=32)
    admin_password = models.CharField(verbose_name="管理员密码", max_length=64)

    def __str__(self):
        return self.admin_name


class Department(models.Model):
    """ 部门表 """
    # id = models.BigAutoField(verbose_name='ID', primary_key=True)  # BigAutoField指的是Big int类型
    # id = models.AutoField(verbose_name='ID', primary_key=True)  # AutoField指的是int类型
    # id 这列不用手动写,django项目会自动创建自增的ID列, 在apps.py文件中AppWebConfig类中有对应的代码.

    department_name = models.CharField(verbose_name='部门名称', max_length=255)  # 使用CharField函数必须跟max_length参数

    def __str__(self):
        return self.department_name
    # 用 __str__返回对应的title


class EmployeeInfo(models.Model):
    """ 员工表 """
    employee_name = models.CharField(verbose_name='姓名', max_length=64)
    employee_password = models.CharField(verbose_name='密码', max_length=64)
    employee_age = models.IntegerField(verbose_name='年龄')  # 使用IntegerField函数不用跟max_length参数
    employee_account = models.DecimalField(verbose_name='账户余额', max_digits=10, decimal_places=2, default=0)
    # max_digits参数表示账户数位是10位, 小数长度为2位. default=0表示默认账户余额为0.
    # create_time = models.DateTimeField(verbose_name="入职时间")
    create_time = models.DateField(verbose_name="入职时间")  # DateField字段只包含年月日,没有时分秒

    # 无约束写法
    # department_id = models.BigIntegerField(verbose_name='部门ID')

    # 1. 有约束写法:
    # - to: 与哪张表关联
    # - to_field: 与表中的列关联
    # 2. django中自动
    # - 写的department
    # - 使用了ForeignKey函数后, 在生成数据库列的时候department会自动变成department_id.
    # 3. 部门表被删除
    # 3.1 级联删除操作--on_delete=models.CASCADE参数表示采用级联删除.
    department = models.ForeignKey(verbose_name="部门", to="Department", on_delete=models.CASCADE)
    # 3.2 置空操作--null=True, blank=True两个参数表示department_id列可以为空,
    # department = models.ForeignKey(to="Department", to_fields="id", null=True, blank=True, on_delete=models.SET_NULL)

    # 在django代码中做的约束
    gender_choices = (
        (1, '男'),
        (2, '女'),
    )
    gender = models.SmallIntegerField(verbose_name="性别", choices=gender_choices)

    """
    department = models.ForeignKey(to="Department", to_fields="id", on_delete=models.CASCADE)  
    改为:
    department = models.ForeignKey(to="Department", on_delete=models.CASCADE)
    """


class PrettyNum(models.Model):
    """ 靓号表 """
    mobile_number = models.CharField(verbose_name="手机号", max_length=32)  # 把手机号存储成字符串类型,方便后期对用户的手机进行正则表达式校验和搜索操作.
    # 想要允许为空, 就在参数中加 null=True, blank=True
    price = models.IntegerField(verbose_name="价格", default=0)  # 价格都是整数

    level_choices = (
        (1, "1级"),
        (2, "2级"),
        (3, "3级"),
        (4, "4级")
    )
    level = models.SmallIntegerField(verbose_name="级别", choices=level_choices, default=1)  # 创建靓号时,没有选级别,默认为1级.

    status_choices = (
        (1, "已占用"),
        (2, "未使用")
    )
    status = models.SmallIntegerField(verbose_name="状态", choices=status_choices, default=2)


class Task(models.Model):
    """ 任务管理 """
    level_choices = (
        (1, "紧急"),
        (2, "重要"),
        (3, "临时")
    )
    task_level = models.SmallIntegerField(verbose_name="级别", choices=level_choices, default=1)
    task_title = models.CharField(verbose_name="任务标题", max_length=64)
    task_detail = models.TextField(verbose_name="任务详情")
    # 数据库中会生成task_responsible_person_id字段
    task_responsible_person = models.ForeignKey(verbose_name="负责人", to="Admin", on_delete=models.CASCADE)


class Order(models.Model):
    """ 订单管理 """
    order_number = models.CharField(verbose_name="订单号", max_length=64)
    product_name = models.CharField(verbose_name="商品名称", max_length=32)
    order_price = models.IntegerField(verbose_name="订单价格")
    order_status_choices = (
        (1, "待支付"),
        (2, "已支付"),
    )
    order_status = models.IntegerField(verbose_name="订单状态", choices=order_status_choices, default=1)
    order_creator = models.ForeignKey(verbose_name="订单创建者", to="Admin", on_delete=models.CASCADE)


class Boss(models.Model):
    """ 老板信息表 """
    boss_name = models.CharField(verbose_name="姓名", max_length=32)
    boss_age = models.IntegerField(verbose_name="年龄")
    boss_image = models.CharField(verbose_name="头像", max_length=128)


class City(models.Model):
    """ 城市信息表 """
    city_name = models.CharField(verbose_name="城市名称", max_length=32)
    city_population = models.IntegerField(verbose_name="城市人口数")
    city_logo = models.FileField(verbose_name="城市Logo", max_length=128, upload_to='city/')
    # FileField字段本质上数据库也是CharField,区别在于用FileField的话文件保存的代码可以不写,django内部自动会做.
    # upload_to=参数表示要上传到media目录下的哪个目录.


class BranchPerformance(models.Model):
    """ 分公司业绩表 """
    branch_name = models.CharField(verbose_name="分公司名称", max_length=32)
    january_performance = models.IntegerField(verbose_name="一月份业绩")
    february_performance = models.IntegerField(verbose_name="二月份业绩")
    march_performance = models.IntegerField(verbose_name="三月份业绩")
    april_performance = models.IntegerField(verbose_name="四月份业绩")
    may_performance = models.IntegerField(verbose_name="五月份业绩")
    june_performance = models.IntegerField(verbose_name="六月份业绩")
    july_performance = models.IntegerField(verbose_name="七月份业绩")
    august_performance = models.IntegerField(verbose_name="八月份业绩")
    september_performance = models.IntegerField(verbose_name="九月份业绩")
    october_performance = models.IntegerField(verbose_name="十月份业绩")
    november_performance = models.IntegerField(verbose_name="十一月份业绩")
    december_performance = models.IntegerField(verbose_name="十二月份业绩")


class EmployeePerformance(models.Model):
    """ 员工业绩表 """

EmployeeManagementSystem_bootstrap3/app_web/views/account_views.py
"""
    登录界面的视图函数
"""
from django import forms
from django.shortcuts import render, HttpResponse, redirect

from io import BytesIO

from app_web import models
from app_web.utils.bootstrap_mf import BootStrapForm
from app_web.utils.encrypt import admin_pwd_md5
from app_web.utils.captcha import captcha


class LoginForm(BootStrapForm):
    admin_name = forms.CharField(  # 可能是admin_name
        label="用户名",
        widget=forms.TextInput,  # (attrs={"class": "form-control"})
        required=True  # 默认不能为空
    )
    admin_password = forms.CharField(  # admin_password
        label="密码",
        widget=forms.PasswordInput(render_value=True),  # 没有下方的init函数,加这个参数可实现效果(attrs={"class": "form-control"})
        required=True  # 默认不能为空
    )

    captcha = forms.CharField(
        label="验证码",
        widget=forms.TextInput,
        required=True  # 默认不能为空
    )

    def clean_admin_password(self):
        admin_pwd = self.cleaned_data.get("admin_password")
        return admin_pwd_md5(admin_pwd)


# class LoginModelForm(forms.ModelForm):
#     class Meta:
#         model = models.Admin
#         fields = ['admin_name', 'admin_password']


def login(request):
    """ 登录 """

    if request.method == "GET":
        form_m = LoginForm()
        return render(request, 'login.html', {'form_m': form_m})

    form_m = LoginForm(data=request.POST)
    if form_m.is_valid():
        # 验证成功后,获取到的用户名和密码
        # print(form_m.cleaned_data)  # {'admin_name': 'jason_7', 'admin_password': '1ddee8b81f96f875279ef2766ef5319b', 'captcha': 'xxxx}

        # 验证码的校验
        user_input_captcha = form_m.cleaned_data.pop('captcha')
        get_captcha_string = request.session.get('image_captcha_string', "")  # 到session中拿到验证码的字符串,内容可能为空,
        if get_captcha_string.upper() != user_input_captcha.upper():
            form_m.add_error("captcha", "验证码错误")
            return render(request, 'login.html', {'form_m': form_m})

        # 去数据库校验用户名和密码是否一致, 获取用户对象, 如果用户名和密码为错误的,得到的对象是空.
        # admin_object_a = models.Admin.objects.filter(admin_name=form_n.cleaned_data['admin_name'], admin_password=form_n.cleaned_data['admin_password']).first()
        admin_object_a = models.Admin.objects.filter(**form_m.cleaned_data).first()
        if not admin_object_a:
            form_m.add_error("admin_password", "用户名或密码错误")
            return render(request, 'login.html', {'form_m': form_m})

        # 用户名密码输入正确,
        # 网站生成随机字符串; 写到用户浏览器的cookie中;再写入到session中,
        request.session["login_info"] = {  # 在服务端的session中,存储是字典类型的login_info信息,里面有登录用户的id和用户名.
            'id': admin_object_a.id,
            'admin_name': admin_object_a.admin_name
        }
        # session可以保存7天
        request.session.set_expiry(60 * 60 * 24 * 7)  # 对session超时进行重新设置, 设置7天免登录

        return redirect("/admin/list/")

    return render(request, 'login.html', {'form_m': form_m})


def image_captcha(request):
    """ 生成图片验证码 """

    # 调用pillow函数,生成图片
    image_c, captcha_string = captcha()
    print(captcha_string)

    # 写入到自己的session中,(以便于后续获取验证码再进行校验)
    request.session['image_captcha_string'] = captcha_string

    # 给session设置60s超时
    request.session.set_expiry(60)

    stream_a = BytesIO()  # 创建数据流文件stream_a在内存中
    image_c.save(stream_a, 'png')  # 将image_c写到stream_a文件中以png的格式

    return HttpResponse(stream_a.getvalue())


def logout(request):
    """ 注销 """

    request.session.clear()

    return redirect('/login/')

EmployeeManagementSystem_bootstrap3/app_web/views/chart_views.py
""" 数据统计图表 视图函数 """
from django.shortcuts import render
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt


def chart_list(request):
    """ 数据统计图表列表 """
    return render(request, 'chart_list.html')


@csrf_exempt
def chart_line(request):
    """ 构造折线图的数据"""

    # 从数据库中获取数据


    # 手动填写数据
    legend = ['上海分公司', '北京分公司', '广州分公司', '深圳分公司', '浙江分公司']

    x_axis = ['1月', '2月', '3月', '4月', '5月', '6月', '7月']

    series_list = [
        {
            "name": '上海分公司',
            "type": 'line',  # 类型:line 表示显示折线图
            "stack": 'Total',
            "data": [120, 132, 101, 134, 90, 230, 210]  # x轴上每一个字段对应的值
        },
        {
            "name": '北京分公司',
            "type": 'line',
            "stack": 'Total',
            "data": [220, 182, 191, 234, 290, 330, 310]
        },
        {
            "name": '广州分公司',
            "type": 'line',
            "stack": 'Total',
            "data": [150, 232, 201, 154, 190, 330, 410]
        },
        {
            "name": '深圳分公司',
            "type": 'line',
            "stack": 'Total',
            "data": [320, 332, 301, 334, 390, 330, 320]
        },
        {
            "name": '浙江分公司',
            "type": 'line',
            "stack": 'Total',
            "data": [820, 932, 901, 934, 1290, 1330, 1320]
        }

    ]

    result = {
        "status": True,
        "data": {
            'legend': legend,
            'x_axis': x_axis,
            'series_list': series_list,
        }
    }

    return JsonResponse(result)


@csrf_exempt
def chart_bar(request):
    """ 构造柱状图的数据 """
    # 数据可以到数据库中获取
    legend = ['高露', '王楚然']

    x_axis = ['1月', '2月', '3月', '4月', '5月', '6月', '7月']

    series_list = [
        {
            "name": '高露',
            "type": 'bar',  # 类型:bar 表示显示柱状图
            "data": [5, 20, 36, 10, 10, 30, 60]  # x轴上每一个字段对应的值
        },
        {
            "name": '王楚然',
            "type": 'bar',
            "data": [15, 50, 56, 20, 30, 20, 55]
        }
    ]

    result = {
        "status": True,
        "data": {
            'legend': legend,
            'x_axis': x_axis,
            'series_list': series_list,
        }
    }

    return JsonResponse(result)


@csrf_exempt
def chart_pie(request):
    """ 构造饼图的数据 """

    db_data_list = [
        {"value": 1048, "name": 'IT部门'},
        {"value": 735, "name": '运营部'},
        {"value": 580, "name": '新媒体部'},
        {"value": 484, "name": '销售部'},
        {"value": 300, "name": '综合部'}
    ]

    result = {
        "status": True,
        "data": db_data_list,
    }

    return JsonResponse(result)


def highcharts_example(request):
    """ highcharts图表示例 """

    return render(request, 'highcharts_example.html')

EmployeeManagementSystem_bootstrap3/app_web/views/city_views.py
""" 城市列表 视图函数 """
from django.shortcuts import render, redirect
from app_web import models
from app_web.utils.bootstrap_mf import BootStrapModelForm


def city_list(request):
    """ 城市列表函数 """
    queryset_a = models.City.objects.all()

    return render(request, 'city_list.html', {'queryset_a': queryset_a})


class UploadModelForm(BootStrapModelForm):
    bootstrap_exclude_fields = ['city_logo']  # 将city_logo字段不使用BootStrapForm样式

    class Meta:
        model = models.City
        fields = "__all__"


def city_add(request):
    """ 基于 ModelForm上传新建城市的文件和数据 """
    upload_title = "新建城市"

    if request.method == "GET":
        form_a = UploadModelForm
        return render(request, 'upload_form.html', {'form_a': form_a, 'upload_title': upload_title})

    form_a = UploadModelForm(data=request.POST, files=request.FILES)
    if form_a.is_valid():
        # 这一句form_a.save()保存代码,对于文件的话会自动保存的
        # 字段 + 上传路径就写入到数据库.
        form_a.save()
        return redirect("/city/list/")

    return render(request, 'upload_form.html', {'form_a': form_a, 'upload_title': upload_title})

EmployeeManagementSystem_bootstrap3/app_web/views/log_views.py
"""
    记录日志的view函数
"""

from django.shortcuts import render, HttpResponse
import logging

# 获取logger对象
logger = logging.getLogger("logger_study.file")


def log_view(request):

    # 日志级别从低到高
    logger.debug('日志测试 debug 级别')
    logger.info('日志测试 info 级别')
    logger.warning('日志测试 warning 级别')
    logger.error('日志测试 error 级别')
    logger.critical('日志测试 critical 级别')
    return HttpResponse('学习Django框架中的日志')

EmployeeManagementSystem_bootstrap3/app_web/templates/city_list.html
{% extends 'layout.html' %}

{% block content %}
<!-- 页面内容区域 -->
    <div class="container">
        <div style="margin-bottom: 10px">
            <a class="btn btn-success" href="/city/add/">
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                新建城市
            </a>
        </div>

        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                城市列表
            </div>

            <!-- Table -->
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>名称</th>
                    <th>人口</th>
                    <th>Logo</th>
                </tr>
                </thead>
                <tbody>
                {% for obj in queryset_a %}
                    <tr>
                        <th>{{ obj.id }}</th>
                        <td>{{ obj.city_name }}</td>
                        <td>{{ obj.city_population }}</td>
                        <td>
                            <img src="/media/{{ obj.city_logo }}" style="height: 80px">
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>

        <ul class="pagination">
        {{ page_string }}
        </ul>

    </div>
{% endblock %}

EmployeeManagementSystem_bootstrap3/app_web/templates/common_add.html
{% extends 'layout.html'%}

{% block content %}
   <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"> {{ add_title }} </h3>
            </div>
            <div class="panel-body">
                <form method="post" novalidate>  <!-- novalidate参数的含义是不显示浏览器提供的校验提示 -->
                    {% csrf_token %}

                    {% for fields in form %}
                        <div class="form-group">
                            <label>{{ fields.label }}</label>
                            {{ fields }}
                            <span style="color: red">{{ fields.errors.0 }}</span>  <!-- 只要显示错误信息中0号索引位的错误信息 -->
                            <!-- <input type="text" class="form-control" placeholder="姓名" name="submit_name"/> -->
                        </div>
                    {% endfor %}

                    <button type="submit" class="btn btn-primary">提交</button>
                    <button type="button" class="btn btn-default" onclick="cancelFunction()">取消</button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}


{% block js %}
    <script>
        function cancelFunction() {
            // 页面导航到
            window.location.href = "http://127.0.0.1:8000/admin/list/";
        }
    </script>
{% endblock %}

EmployeeManagementSystem_bootstrap3/app_web/templates/department_model_form_add.html
{% extends 'layout.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-datepicker/css/bootstrap-datepicker.css' %}">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"> 新建部门 </h3>
            </div>
            <div class="panel-body">
                <form method="post" novalidate>  <!-- novalidate参数的含义是不显示浏览器提供的校验提示 -->
                    {% csrf_token %}

                    {% for fields in form %}
                        <div class="form-group">
                            <label>{{ fields.label }}</label>
                            {{ fields }}
                            <span style="color: red">{{ fields.errors.0 }}</span>  <!-- 只要显示错误信息中0号索引位的错误信息 -->
                            <!-- <input type="text" class="form-control" placeholder="姓名" name="submit_name"/> -->
                        </div>
                    {% endfor %}

                    <button type="submit" class="btn btn-primary">提交</button>
                    <button type="button" class="btn btn-default" onclick="cancelFunction()">取消</button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

{% block js %}
    <script rel="stylesheet" src="{% static 'plugins/bootstrap-datepicker/js/bootstrap-datepicker.js' %}"></script>
    <script rel="stylesheet" src="{% static 'plugins/bootstrap-datepicker/locales/bootstrap-datepicker.zh-CN.min.js' %}"></script>
    <script>
        $(function () {
            $('#id_create_time').datepicker({
                format: 'yyyy-mm-dd',
                startDate: '0',
                language: "zh_CN",
                autoclose: true
                });
        })

        function cancelFunction() {
            // 页面导航到
            window.location.href = "http://127.0.0.1:8000/department/list/";
        }

    </script>

{% endblock %}

EmployeeManagementSystem_bootstrap3/app_web/templates/error.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <div class="alert alert-danger" role="alert">{{ error_message }}</div>
    </div>
{% endblock %}

EmployeeManagementSystem_bootstrap3/app_web/templates/prettynum_list.html
{% extends 'layout.html' %}

{% block content %}
    <!-- 页面内容区域 -->
    <div class="container">
        <div style="margin-bottom: 10px" class="clearfix">
            <a class="btn btn-success" href="/prettynum/model/form/add/">
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                新建靓号
            </a>

            <div style="float: right; width:300px">
                <form method="get">
                    <div class="input-group">
                        <input type="text" name="user_search" class="form-control" placeholder="Search for..." value="{{ search_data }}">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="submit">
                                <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                            </button>
                        </span>
                    </div><!-- /input-group -->
                </form>
            </div>

        </div>

        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                靓号列表
            </div>

            <!-- Table -->
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>号码</th>
                    <th>价格</th>
                    <th>级别</th>
                    <th>状态</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for obj in queryset_d %}
                    <tr>
                        <th>{{ obj.id }}</th>
                        <td>{{ obj.mobile_number }}</td>
                        <td>{{ obj.price }}</td>
                        <td>{{ obj.get_level_display }}</td>
                        <td>{{ obj.get_status_display }}</td>
                        <td>
                            <a class="btn btn-primary btn-xs" href="/prettynum/{{ obj.id }}/edit/">编辑</a>
                            <!-- <a class="btn btn-danger btn-xs" href="/prettynum/{/delete/">删除</a> -->
                            <input prettynum_id="{{ obj.id }}" class="btn btn-danger btn-xs btn-delete" type="button" value="删除">
                        </td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>

        <div class="clearfix">
            <ul class="pagination">
                {{ page_string }}
                <!-- <li>
                    <form style="float: left; margin-left: -1px" method="get">
                        <input  name="current_page" style="position: relative; float: left; display: inline-block; width: 80px; border-radius: 0;"
                                type="text" class="form-control" placeholder="页码">
                    <button class="btn btn-default" type="submit">跳转</button>
                    </form>
                </li>
                -->

            </ul>
        </div>
    </div>


        <!-- 删除确认(对话框)   -->
    <!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel">
        <div class="modal-dialog" role="document">

            <div class="alert alert-danger alert-dismissible fade in" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                        aria-hidden="true">×</span></button>
                <h4>是否确定删除 ?</h4>
                <p style="margin: 10px 0px;">删除后, 所有关联的数据都会被删除</p>
                <p style="text-align: right;">
                    <button id="btnConfirmDelete" type="button" class="btn btn-danger">确 定</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">取 消</button>
                </p>
            </div>

        </div>
    </div>

{% endblock %}



{% block js %}
    <script type="text/javascript">

        var DELETE_ID;

        $(function () {
            bindBtnDeleteEvent();
            bindBtnConfirmDeleteEvent();
        })

        function bindBtnDeleteEvent() {
            $(".btn-delete").click(function () {
                // alert("已点击删除")
                // 显示删除对话框
                $("#deleteModal").modal('show');

                // 获取当前行的ID,并赋值给全部变量
                // var orderId = $(this).attr("orderid");
                // console.log(orderId);
                DELETE_ID = $(this).attr("prettynum_id");
            });
        }

        function bindBtnConfirmDeleteEvent() {
            $("#btnConfirmDelete").click(function () {
                // 点击确认删除按钮, 将全局变量中设置的那个要删除的ID发送到后台.
                $.ajax({
                    // url: "/order/" + DELETE_ID + "/delete/",  //    => /order/123/delete/   这是另外一种方式
                    url: "/prettynum/delete/",  //  => /order/delete/?orderid=123
                    data: {
                        prettynum_id: DELETE_ID
                    },
                    type: "GET",
                    dataType: "JSON",
                    success: function (res) {
                        if (res.status){
                            // 删除成功
                            alert("删除成功");

                            // 第一种处理删除对话框和页面更新的方法:比较有条理的方法
                            // 隐藏删除对话框
                            // $("#deleteModal").modal('hide');
                            // 在页面上将当前这一行数据删除显示(js)
                            // $("tr[orderid='" + DELETE_ID + "']").remove();
                            // 将要删除的ID置空
                            // DELETE_ID = 0;

                            // 第二种处理删除对话框和页面更新的方法:更简单的思路,删除成功后,让页面刷新
                            location.reload();
                        } else {
                            // 删除失败
                            alert(res.error);
                        }
                    }
                })
            });
        }

    </script>
{% endblock %}